name: Zig Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        zig-version: [0.14.0]
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@main
        with:
          version: ${{ matrix.zig-version }}

      - name: Build library
        run: zig build

      - name: Run tests
        run: zig build test --summary all